### ISSUE TITLE
Incorrect highlighting of dashed values

### ISSUE THREAD

**Issue by madeleineostoja** [xekri/vscode-styled-jsx#10]
vscode-styled-jsx incorrectly highlights any values with dashes in them, including CSS vars

<img width="357" alt="screen shot 2018-07-07 at 9 57 13 pm" src="https://user-images.githubusercontent.com/6374876/42410680-ef64d4da-8230-11e8-9383-8399b2b3508c.png">

**Comment by iFwu** [comment]
![code](https://user-images.githubusercontent.com/16523864/45221641-a9736600-b2e4-11e8-9135-11dfd54ba7a0.png)
fixed in new version
