### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by dizlexik** [xekri/vscode-styled-jsx#17]
I'm not sure why but this extension has stopped working for me recently. I've done nothing other than upgrade VS Code to the latest version (currently v1.28.2). And I've tried reinstalling vscode-styled-jsx, but no luck.

Am I doing anything obviously wrong here?

![image](https://user-images.githubusercontent.com/300104/47813314-b165ea00-dd18-11e8-9362-f2b8f25c7ddf.png)

I really miss the syntax highlighting and intellisense :/

**Comment by iFwu** [comment]
Hello, did you install any extension that may replace internal JavaScript language highlight?
Can you use` Developer: Inspect TM Scopes` tool to inspect the token in the grave accent like below?


![](https://user-images.githubusercontent.com/16523864/47703598-bca71000-dc5b-11e8-9367-7c5e792b68ac.png)

![](https://user-images.githubusercontent.com/16523864/47703616-ce88b300-dc5b-11e8-9c50-809ab52ce332.png)

**Comment by dizlexik** [comment]
Thanks for pointing me in the right direction. I think I found the problem. The styled-jsx syntax highlighting starts working when I disable the Babel JavaScript extension. I wonder what made it stop working, though, because I've had the extension for a very long time, like before I never had vscode-styled-jsx. Any ideas? Here's my scope inspector output, in case it helps:

![image](https://user-images.githubusercontent.com/300104/47869163-382bcd00-ddd4-11e8-801f-22d8a83f818b.png)

**Comment by iFwu** [comment]
@dizlexik It may relate to vscode upgrade, I'm not sure. However, babel highlighting seems no longer maintained for a long time, I think the internal JS syntax highlighting is good enough.

**Comment by dizlexik** [comment]
The babel extension I'm using, [Babel JavaScript](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel), is actually really nice and is actively maintained. It's quite popular and I imagine lots of other vscode-styled-jsx users are probably using it as well and running into the same issue that I'm experiencing. I'd really love to have both of these working at the same time if possible. Many of my React component files have both styled-jsx and graphql fragments in them but as it stands right now I can only get syntax highlighting on one or the other by enabling/disabling Babel JavaScript. @iFwu, is there any chance you might give this a second look? Thanks.

**Comment by iFwu** [comment]
OK, I'll look into it.

**Comment by davidubanyi** [comment]
Hi @iFwu any updates on this? I have the same challenge.

**Comment by zoro00000000** [comment]
This problem does, I hope solved

**Comment by RalphSimon** [comment]
Hey there,

The vscode-babel-language extension allows for syntax highlighting in styled-components and such, by adding the */* CSS */* comment before your template string:

![image](https://user-images.githubusercontent.com/8267194/53586047-9e104180-3b87-11e9-8109-60a97d20aeaf.png)

> styled-components, emotion CSS inside tagged template strings plus additional highlighting via /* CSS */ comment
[vscode-babel-language](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel)

**Comment by stuart-williams** [comment]
I'm seeing broken highlighting for resolved styles only

![Screenshot 2019-04-17 at 09 26 48](https://user-images.githubusercontent.com/2526507/56272629-093fb400-60f3-11e9-93a9-2b3ea857ce1b.png)

**Comment by mezzario** [comment]
Have same issue:

![image](https://user-images.githubusercontent.com/2454284/62597140-e3a10b00-b899-11e9-9228-3504c5f4fe39.png)

If you move `style` tag to the gutter (opening tag or whole block) it will fix highlighting:

![image](https://user-images.githubusercontent.com/2454284/62597201-14814000-b89a-11e9-99ea-2db7845312cf.png)

**Comment by spacecakes** [comment]
Yes, resolved styles lack highlighting for me too.

**Comment by ansh** [comment]
this is still an issue

**Comment by taurikalve** [comment]
I've found a fix.

In **jsx-styled.json**

Located in (Windows):
`%userprofile%\.vscode\extensions\blanu.vscode-styled-jsx-1.5.0\syntaxes`

Change
`"begin": "(?:(<)(style) (jsx)(>))|(?:(<)(style) (jsx global)(>))|(?:(<)(style) (global jsx)(>))",`
to:
`"begin": "\\s*(<)(style) (jsx)(>)|\\s*(<)(style) (global jsx)(>)|\\s*(<)(style) (jsx global)(>)",`

For me the language server works properly too now, it showed some weird syntax errors before.

**Comment by iFwu** [comment]
> I've found a fix.
> 
> In **jsx-styled.json**
> 
> Located in (Windows):
> `%userprofile%\.vscode\extensions\blanu.vscode-styled-jsx-1.5.0\syntaxes`
> 
> Change
> `"begin": "(?:(<)(style) (jsx)(>))|(?:(<)(style) (jsx global)(>))|(?:(<)(style) (global jsx)(>))",`
> to:
> `"begin": "\\s*(<)(style) (jsx)(>)|\\s*(<)(style) (global jsx)(>)|\\s*(<)(style) (jsx global)(>)",`
> 
> For me the language server works properly too now, it showed some weird syntax errors before.

Thanks for providing this info, when I have time I'll fix it.

**Comment by jeado** [comment]
> I've found a fix.
> 
> In **jsx-styled.json**
> 
> Located in (Windows):
> `%userprofile%\.vscode\extensions\blanu.vscode-styled-jsx-1.5.0\syntaxes`
> 
> Change
> `"begin": "(?:(<)(style) (jsx)(>))|(?:(<)(style) (jsx global)(>))|(?:(<)(style) (global jsx)(>))",`
> to:
> `"begin": "\\s*(<)(style) (jsx)(>)|\\s*(<)(style) (global jsx)(>)|\\s*(<)(style) (jsx global)(>)",`
> 
> For me the language server works properly too now, it showed some weird syntax errors before.

it works for me

**Comment by iFwu** [comment]
I've published the fix in v2.0.0. Thanks for helping.
