### ISSUE TITLE
Doesn't syntax highlight when css.global`...` is used

### ISSUE THREAD

**Issue by Macil** [xekri/vscode-styled-jsx#20]
The plugin doesn't do any syntax highlighting for either of these files:

```js
/* @flow */

import css from 'styled-jsx/css';

export default css.global`
  foo {
    color: red;
  }
`;
```

```js
/* @flow */

import {global} from 'styled-jsx/css';

export default global`
  foo {
    color: red;
  }
`;
```

It correctly syntax highlights if css\`...\` is used.

**Comment by ywg-jean** [comment]
@Macil I had the same issue. 
After I uninstalled the extension and reinstalled it and it started highlighting styled wrapped with css.global``

**Comment by WestonThayer** [comment]
Same here, but reinstalling doesn't help. Also seems to happen for `css.resolve`.

**Comment by WestonThayer** [comment]
Heh, I think it's a regex issue. `.resolve` works, but adding `css` in front of it doesn't.

![GIF](https://user-images.githubusercontent.com/709153/57321272-d8c9b500-70b5-11e9-8ba2-6cd224e2b180.gif)
