### ISSUE TITLE
Not working when putting template literals on their own line

### ISSUE THREAD

**Issue by arielger** [xekri/vscode-styled-jsx#5]
When opening the template literals at the same line as the opening `<style jsx>` tag everything works fine:

![image](https://user-images.githubusercontent.com/6318057/34084190-244bc426-e35b-11e7-8320-1756ba709bb5.png)

but after running Prettier it moves the JSX expression with the template literal to a new line and the highlighting stops working:

![image](https://user-images.githubusercontent.com/6318057/34084197-6c4e97e4-e35b-11e7-95f7-51e47614a399.png)

Thanks for your work on this plugin.

**Comment by arielger** [comment]
You can check in this example how Prettier will format the code
https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAJOBDAEzgCdMBeTACgEpyA+KgHSk0wB4ALARjudddyESffmwwBPADZxMAKzQAPOsAAGI-pm6Zg6jZkiSIxJJmJwCAbl2sAvrpV2WogPQTpvJ22fcP1K1BAAGhAIAAcYAEt0ZFA8YmIIAHcABTiENGQQPAA3CAiCIKyMZAAzPEk0OGCAI2I8MABrOBgAZVD6iKgAc2QYYgBXKpACCDBS8srgzsriGGS6roBbPHGKofkFACE6xuaWvEW4ABlOuFXJkP6YUKuAJnOh9uIZzOq8aqloQtDiTpgAdXyMA4yAAHAAGYI-CCVf51UKZH5wGbZM7BMwAR36ETM8zwSxWSDKa2ClUWEV6AyGaE6XWkAEV+hB4A9gjB3oCCMDkLc2XUIpJaQBhCCLZaZKDQNEgfqVAAq7wyRImcBsNiAA

**Comment by oskari** [comment]
@arielger Did you find any solution to this?

@iFwu Any plans on fixing this?

**Comment by GabeDuarteM** [comment]
That is happening with me as well, is someone looking into this?

**Comment by u3u** [comment]
@oskari @GabrielDuarteM 
Prettier has improved this issue, see: https://github.com/prettier/prettier/issues/1090

https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAJOBDAEzgCdMBeTACgEpyA+KgHSk0wB4ALARjudddyESffmwwBPADZxMAKzQAPOsAAGI-pm6Zg6jZkiSIxJJmJwCAbl2sAvrpV2WogPQTpvJ22fcP1K1GZIKAwcfCJSChp6Jk8fXUFw3TEYKRl5JVVrTS5tLNYDIxMzSyzHDQcvNzgPVi84qD9mEAAaEAgABxgAS3RkUDxiYggAdwAFAYQ0ZBA8ADcILoIWkAAjYjwwAGs4GABldo2uqABzZBhiAFc4VqO0EhhR9eOAWzxkADM8STvW9IAhdZbHa7PDPOAAGSOcA+Xx+IAOxDuxGmKzwKyk0GW7WIRxgAHVFjAOMgABwABla2Igdzx63a02xcCRs2hrTMAEcLl0zI88C83khPt9riA7s8umdLiK0EdjtIAIoXCDwGHC1owNEEghE5AAJnV6y6kllAGEIM9XtMoNBWSALncACpoqaC2EivAYVVwggQMBekUQC4wdpB3X+mw2IA

**Comment by GabeDuarteM** [comment]
@u3u Its not for all cases, but there are some where this still occur, like [this example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEB1AllAEwgHc1MBeTACgEoKA+agHSk0wB4DcA3TMAGwCGaNADlBAWzjkmIYviKkAtACcIEGLPos2bdgBVhAawBGglZgD021rvYYAnvziYAVmgAe9YAAMdugIA6eUISNFV1LGB-AICACzhcAHM4mCRMAEYABizuOIBuGNi2MzAjJLUAV0IlXAlBJLh0ypV+KksMQRhcMEs6pMsQxXDS8qrCQNcABySaQttiksEyiohqgiU0XAAvJr4IbjgVecXMAF8ith8LhY4OmCc4Gz1LLm4bGhAAGhAIKe70MhQOY1MQAArmBBoZAgQTcCC4AjfEAmFTLIxwGAAZSmy3wSWQMBUlTgP3waCOMDBaKS9WQADNBPwKT93B4AEJosqYrGSOAAGXwcAZTJZIFxKgpKhhZhMTmgyKmKnwMDwBBgcWQAA4sj8lRAKdg0VMYUq4FLDsiVHAAI6VXDW6kNOlIRnM0kgCkSXCE4kerZQJLOACKlQ0wtdoo9MEEJjVGuQACYfkTBLh+PiAMIQCQukBQaDCn6VCmGEzQyPun7CGAiqsgIhgOtitYwKaVGCJ5twM5nIA)

prettier formats 
```
const Windows = () => (
  <div className="windows-root">
    <Taskbar />
    <style jsx>{`
        .windows-root {
          height: 100vh;
          background-image: url(/static/img/windows-background.jpg);
          background-size: cover;
        }
      `}
    </style>
  </div>
)
```

to this

```
const Windows = () => (
  <div className="windows-root">
    <Taskbar />
    <style jsx>
      {`
        .windows-root {
          height: 100vh;
          background-image: url(/static/img/windows-background.jpg);
          background-size: cover;
        }
      `}
    </style>
  </div>
);
```

Anyway, would it be hard to fix this and allow both ways? Because even if i didn't use prettier, the second code is still a valid styled jsx syntax...

**Comment by u3u** [comment]
@GabrielDuarteM You need to write `}</style> on the same line

```diff
const Windows = () => (
  <div className="windows-root">
    <Taskbar />
    <style jsx>{`
        .windows-root {
          height: 100vh;
          background-image: url(/static/img/windows-background.jpg);
          background-size: cover;
        }
-      `}
-    </style>
+     `}</style>
  </div>
)
```

to this

```js
const Windows = () => (
  <div className="windows-root">
    <Taskbar />
    <style jsx>{`
      .windows-root {
        height: 100vh;
        background-image: url(/static/img/windows-background.jpg);
        background-size: cover;
      }
    `}</style>
  </div>
);
```

Please see this [example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEB1AllAEwgHc1MBeTACgEoKA+agHSk0wB4DcA3TMAGwCGaNADlBAWzjkmIYviKkAtACcIEGLPos2bdgBVhAawBGglZgD021rvYYAnvziYAVmgAe9YAAMdugIA6eUISNFV1LGB-AICACzhcAHM4mCRMAEYABizuOIBuGNi2MzAjJLUAV0IlXAlBJLh0ypV+KksMQRhcMEs6pMsQxXDS8qrCQNcABySaQttiksEyiohqgiU0XAAvJr4IbjgVecXMAF8ith8z9g6YJzgbPUsubhsaEAAaEAgp7vRkKBzGpiAAFcwINDIECCbgQXAEL4gEwqZZGOAwADKU2W+CSyBgKkqcG++DQRxgoNRSXqyAAZoJ+OTvu4PAAhVFlDGYyRwAAy+Dg9MZzJAOJU5JU0LMJic0CRUxU+BgeAIMDiyAAHFlvoqIOTsKiptDFXBJYckSo4ABHSq4K1Uhq0pAMpkkkDkiS4AlE91bKBJZwARUqGiFLpF7pgghMqvVyAATN9CYJcPw8QBhCASZ0gKDQIXfSrkwwmKERt3fYQwYWVkBEMC10VrGBTSowBNNuBnM5AA)

**Comment by GabeDuarteM** [comment]
@u3u Well, this works and solves my problem, but I still think that this is a workaround to a scenario that the extension does not cover, but should, because it works perfectly with well with `styled-jsx`...

**Comment by u3u** [comment]
@GabrielDuarteM 
Yes, this is just a solution.
This extension should improve it.

**Comment by iFwu** [comment]
Know that, I'll try to fix it, any merge request is welcome (it's nicer if provide test case).

**Comment by mjoynes-wombat-web** [comment]
I know this isn't the most robust and safe method but it works for me. I am not very good at regex so I know it needs improvement but it works whether the {` is on the same line or not.

Begin:
```
"(?<=<style jsx global>)[\\n]*[\\s]*|(?<=<style jsx>)[\\n]*[\\s]*|(?<=<style global jsx>)[\\n]*[\\s]*"
```

End:
```
"(?<=`})[\\n]*[\\s]*"
```

Issues:
The 
```
{`
```
and
```
`}
```
don't highlight properly.

**Comment by mjoynes-wombat-web** [comment]
Also to support the css.global, css and css.resolve another rule needs to be added with the following begin and end. I know the .global and .resolve should probably be in the group with css but when I add it in the rules don't work. As I said, I'm not that good at regex.

Begin:
```
"(?<=css)\\.global`|(?<=css)`|(?<=css)\\.resolve`",
```

End:
```
"(?<=`;)[\\n]*[\\s]*"
```

Issues:
The `.global` and `.resolve` don't highlight properly as well as the `.

**Comment by atombender** [comment]
This issue seems to still exist and should be reopened.

**Comment by iFwu** [comment]
> This issue seems to still exist and should be reopened.

@atombender Could you show me an example code of this issue? I can't reproduce it.

**Comment by pkrawc** [comment]
![screen shot 2018-10-29 at 8 57 24 am](https://user-images.githubusercontent.com/7158581/47654401-bda34900-db58-11e8-99dd-7890d0a9ffab.png)

Screenshot of issue.

vscode-styled-jsx v1.0.0
vscode v1.29.0-insider

**Comment by pkrawc** [comment]
I've also got prettier enabled.

**Comment by pkrawc** [comment]
I've also got prettier enabled.

**Comment by iFwu** [comment]
@pkrawc I can't repeat this problem, can you use `Developer: Inspect TM Scopes` tool to inspect the token in the grave accent like below?
![image](https://user-images.githubusercontent.com/16523864/47703598-bca71000-dc5b-11e8-9367-7c5e792b68ac.png)
![image](https://user-images.githubusercontent.com/16523864/47703616-ce88b300-dc5b-11e8-9c50-809ab52ce332.png)

**Comment by atombender** [comment]
I found the cause for the problem in my case. I had [this](https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring) extension enabled for extended JS syntax highlighting. It takes over the `javascript` mode. Disabling the extension and using the built-in JS syntax works.
